### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Hellowlol** [Hellowlol/hass-AMS#1]
- [ ] Make this use less cpu
- [ ] Make sure setting is possible to set
- [ ] Rename package, or change doc as this only works on kamstrup ams
- [ ] Split the parsing from the home assistant data 
- [ ] Fix yaml mode (is broken)
- [ ] remove platform schema as it isnt used.
- [ ] Add support for all ams (Aidon, Kamstrup and ...)
